name: staart-test
favicon: null
layout_spectrum: 0.09746532584540546
typography_spectrum: 0.2571729721967131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.004676188575103879
  lightness: 0.32212319993413985
  saturation: 0.44404608896002173
  rhythmicContrast: 0.0562816122546792
purpose: []
